spring:
  application:
    name: ai-rag-chatbot

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ragdb}
    username: ${DB_USERNAME:raguser}
    password: ${DB_PASSWORD:ragpassword}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
        temperature: 0.0
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 1000

app:
  security:
    upload-username: ${UPLOAD_USERNAME:admin}
    upload-password: ${UPLOAD_PASSWORD:admin123}
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://frontend-ai-rag-chatbot.vercel.app
      - ${CORS_ALLOWED_ORIGIN:}

server:
  port: ${PORT:8080}
